name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prep
      run: |
        # TBD
    - name: make
      run: make
    - name: make check
      run: |
        make clean
        make
        # needs emulator
        # make SANITIZE=address check
    - name: make check clang
      run: |
        make clean
        make
        # needs emulator
        # make CC=clang SANITIZE=address check
